---
- name: install dependency packages
  apt:
    name: apt-transport-https
- name: add apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: add repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_distribution_release }} main
    filename: nodesource
    state: present
- name: install node.js
  apt:
    name: nodejs
    default_release: "{{ ansible_distribution_release }}"
